- config/_default/config.toml
- config/production/config.toml
- layouts/partials/sidebar/auto-collapsible-menu.html
> fix bad links

- content/en/api.md
- content/en/docs/livePreview/_index.md
- content/en/docs/livePreview/livePreview.md
Add pages for `api` and `livePreview`
> Add blank page to remove 404 error

- .github/workflows/comment_pr.yml
- .github/workflows/python/verify_cla_signature_pr.py
- .github/workflows/verify_cla_signature_pr.yml
Add check that validates that the pull request raiser has signed the CLA and every commit in the pull request belongs to a user that has signed the CLA .
Solve issue task 1 in issue https://github.com/phcode-dev/contributor-license-agreement/issues/6#issue-1221770881
> Add cla checks

- config/_default/params.toml
> chore: update copyright

- config/_default/params.toml
- content/en/docs/features/live-preview.md
> feat: update SEO details

- .github/workflows/gh-pages-deploy.yml
- docusaurus.config.js
github pages deploy for docusaurus
> feat: github pages deploy for docusaurus

- docusaurus.config.js
> fix: update base url

- docusaurus.config.js
change base url to  / for testing
> chore: change base url to  / for testing

- README.md
- package-lock.json
> chore: update build steps in ReadMe

- docs/intro.md
add documentation for getting started
> doc: add doccumtation for getting started

- docs/intro.md
> docs: update getting started

- docusaurus.config.js
- package-lock.json
- package.json
> chore: add google analytics

- src/pages/index.js
> chore: update meta info

- docusaurus.config.js
> chore: change twiter name to X

- docusaurus.config.js
> fix: X url

- docs/03-Features/05-quick-edit.md
- src/components/Video/player.js
1. update video player for custom titles for windows and mac
> feat: update video player

- src/components/Video/player.js
Prevent video title from overlapping the video, improving readability.
> Fix: video title overlap with video

- package-lock.json
- package.json
use `npm run serveStatic`to run a static server on the `build` folder after `npm run build`.
> build: add serveStatic npm run script

- package-lock.json
- package.json
> Chore : update docusaurus to 3.7

- package-lock.json
- package.json
> Chore: Upgrade packages

- package-lock.json
- package.json
This reverts commit 7f50b74514067b6084e6155e42c871042b8a1b40.
Brief explanation of the proposed changes.
Include a basic example, screenshots, or links.
Why are we doing this? What use cases does it support? What is the expected outcome?
> Revert "fix(deps): update react monorepo to v19"
